@IsTest
private class BenchmarkJobSettingSelectorTest {
	@IsTest
	static void shouldRetrieveAllInOrg() {
		Assert.fail('You still need to build this test');
	}

	@IsTest
	static void shouldOnlyQueryOnce() {
		Assert.fail('You still need to build this test');
	}

	@IsTest
	static void shouldReturnInjectedResults() {
		Assert.fail('You still need to build this test');
	}

	@IsTest
	static void shouldReturnRecordByClassName() {
		Assert.fail('You still need to build this test');
	}
}
